name: Pull-Request workflow

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one liner
        run: echo Hello from PR-workflow!
